services:

  db:
    image: mysql:8.0
    container_name: mysql_fotografia
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    container_name: django_fotografia
    restart: always

    command: >
      sh -c "
      sleep 20 &&
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn config.wsgi:application --bind 0.0.0.0:8000
      "

    volumes:
      - .:/app
      - static_volume:/app/staticfiles