# Generated by Django 5.0 on 2026-03-13 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escuelas', '0005_grupo_fecha_fotografia_grupo_hora_fotografia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anillo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('metal', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos', to='catalogo.seccion')),
                ('tipo_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos', to='catalogo.tipoproducto')),
            ],
        ),
        migrations.CreateModel(
            name='AnilloGeneracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('anillo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='catalogo.anillo')),
                ('generacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuelas.generacion')),
            ],
            options={
                'unique_together': {('anillo', 'generacion')},
            },
        ),
        migrations.CreateModel(
            name='ProductoGeneracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('generacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuelas.generacion')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='catalogo.modelo')),
            ],
            options={
                'unique_together': {('modelo', 'generacion')},
            },
        ),
    ]
