# Generated by Django 5.0 on 2026-03-13 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TipoProducto',
            new_name='TamanoProducto',
        ),
        migrations.RenameField(
            model_name='modelo',
            old_name='tipo_producto',
            new_name='tamano_producto',
        ),
    ]
