# Generated by Django 5.0 on 2026-03-13 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_rename_tipoproducto_tamanoproducto_and_more'),
        ('escuelas', '0005_grupo_fecha_fotografia_grupo_hora_fotografia_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductoGeneracion',
            new_name='PrecioGeneracion',
        ),
    ]
