# Generated by Django 5.0 on 2026-03-13 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_rename_productogeneracion_preciogeneracion'),
        ('escuelas', '0005_grupo_fecha_fotografia_grupo_hora_fotografia_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrecioGeneracion',
            new_name='PrecioBaseGeneracion',
        ),
        migrations.CreateModel(
            name='PrecioAnilloGeneracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('anillo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.anillo')),
                ('generacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuelas.generacion')),
            ],
            options={
                'unique_together': {('anillo', 'generacion')},
            },
        ),
        migrations.DeleteModel(
            name='AnilloGeneracion',
        ),
    ]
