# Generated by Django 5.0 on 2026-03-12 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Generacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('anio', models.IntegerField(unique=True)),
            ],
            options={
                'ordering': ['-anio'],
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='escuelas.escuela')),
                ('generacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='escuelas.generacion')),
            ],
        ),
    ]
