# Generated by Django 5.0 on 2026-03-13 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0002_grupo_grupo_unico_por_escuela'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grupo',
            options={'ordering': ['escuela', 'nombre']},
        ),
        migrations.RemoveConstraint(
            model_name='grupo',
            name='grupo_unico_por_escuela',
        ),
    ]
