# Generated by Django 5.0 on 2026-03-13 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0003_alter_grupo_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='grupo',
            constraint=models.UniqueConstraint(fields=('nombre', 'escuela'), name='grupo_unico_por_escuela'),
        ),
    ]
