# Generated by Django 5.0 on 2026-03-13 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0004_grupo_grupo_unico_por_escuela'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='fecha_fotografia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grupo',
            name='hora_fotografia',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grupo',
            name='lugar_fotografia',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
