# Generated by Django 5.0 on 2026-03-31 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0005_grupo_fecha_fotografia_grupo_hora_fotografia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='escuela',
            name='generaciones',
            field=models.ManyToManyField(related_name='escuelas', to='escuelas.generacion'),
        ),
    ]
