# Generated by Django 5.0 on 2026-04-08 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0006_escuela_generaciones'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='grupo',
            name='grupo_unico_por_escuela',
        ),
        migrations.AddConstraint(
            model_name='grupo',
            constraint=models.UniqueConstraint(fields=('nombre', 'escuela', 'generacion'), name='grupo_unico_por_escuela_generacion'),
        ),
    ]
