# Generated by Django 5.0 on 2026-03-13 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escuelas', '0005_grupo_fecha_fotografia_grupo_hora_fotografia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('folio_fotos', models.CharField(blank=True, help_text='Folio o folios de las fotos del alumno', max_length=100)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='escuelas.grupo')),
            ],
        ),
    ]
