# Generated by Django 5.0 on 2026-04-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
        ('escuelas', '0007_remove_grupo_grupo_unico_por_escuela_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='alumno',
            constraint=models.UniqueConstraint(fields=('nombre', 'grupo'), name='alumno_unico_por_grupo'),
        ),
    ]
