# Generated by Django 5.0 on 2026-03-20 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_rename_preciogeneracion_preciobasegeneracion_and_more'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-id'], 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='pedidoitembase',
            options={'ordering': ['id'], 'verbose_name': 'Item base del pedido', 'verbose_name_plural': 'Items base del pedido'},
        ),
        migrations.AlterField(
            model_name='pedidoitembase',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_pedido_base', to='catalogo.modelo'),
        ),
        migrations.AlterField(
            model_name='pedidoitembase',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pedidoitembase',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.CreateModel(
            name='PedidoItemAnillo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamano_anillo', models.DecimalField(decimal_places=1, help_text='Ejemplos: 5, 5.5, 6, 6.5', max_digits=4)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('anillo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_pedido_anillo', to='catalogo.anillo')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_anillo', to='ventas.pedido')),
            ],
            options={
                'verbose_name': 'Item anillo del pedido',
                'verbose_name_plural': 'Items anillo del pedido',
                'ordering': ['id'],
            },
        ),
    ]
