# Generated by Django 5.0 on 2026-03-20 23:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='observaciones',
        ),
        migrations.AddField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de emisión del pago'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pago',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de registro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pago',
            name='folio_nota',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Folio de la nota/recibo'),
        ),
    ]
