# Generated by Django 5.0 on 2026-03-31 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_remove_pago_fecha_remove_pago_observaciones_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoItemExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_extra', to='ventas.pedido')),
            ],
            options={
                'verbose_name': 'Item Extra',
                'verbose_name_plural': 'Items Extra',
            },
        ),
    ]
