# Generated by Django 5.0 on 2026-04-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_pedidoitemextra'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedidoitembase',
            options={},
        ),
        migrations.AddField(
            model_name='pedidoitembase',
            name='color_placa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pedidoitembase',
            name='placa',
            field=models.CharField(blank=True, choices=[('mediterranea', 'Mediterránea'), ('4_piezas', '4 piezas'), ('extendida', 'Extendida'), ('corte_plano', 'Corte plano'), ('palermo', 'Palermo'), ('circulo', 'Círculo'), ('corazon', 'Corazón'), ('estrella', 'Estrella'), ('columnas', 'Columnas'), ('pergamino', 'Pergamino')], max_length=20, null=True),
        ),
    ]
