# Generated by Django 5.0 on 2026-04-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_observacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('listo', 'Listo para entregar'), ('entregado', 'Entregado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='recibido_por',
            field=models.CharField(blank=True, help_text='Nombre de la persona que recibe el pedido', max_length=150, null=True),
        ),
    ]
