# Generated by Django 5.0 on 2026-05-13 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0009_pedidodescuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='actualizado',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='notas_entrega',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('proceso', 'En proceso'), ('listo', 'Listo para entregar'), ('entregado', 'Entregado')], db_index=True, default='pendiente', max_length=20),
        ),
    ]
